[package]
name = "copyup"
version = "0.1.0"
authors = ["Matthew Carey <matthew.b.carey@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
serde = "1.0"
serde_json = "1.0"
strsim = "0.9.2"
clap = "2.31.2"